

--±í
select * from LIMSTABLES where TABLENAME = 'ORDTASK'

--×Ö¶Î
select * from LIMSTABLEFIELDS f
left join LIMSTABLERESOURCES r on f.TABLEID = r.TABLEID and f.FIELDID = r.FIELDID and r.LANGID = 'CHS'
where f.TABLEID = 'FFC873DB-27D8-D34B-BBBB-FEFFC26B90CC'

--Ë÷Òý
select * from LIMSTABLEINDEXES i where i.TABLEID = 'FFC873DB-27D8-D34B-BBBB-FEFFC26B90CC'

--Ë÷Òý×Ö¶Î
select * from LIMSTABLEINDEXES i
left join LIMSTABLEINDEXFIELDS idf on i.TABLEID = idf.TABLEID and i.INDEXID = idf.INDEXID
left join LIMSTABLEFIELDS f on idf.TABLEID = f.TABLEID and idf.FIELDID = f.FIELDID
where i.TABLEID = 'FFC873DB-27D8-D34B-BBBB-FEFFC26B90CC'


select * from LIMSTABLECALLS

select * from LIMSTABLEFIELDSCRIPTS

select * from LIMSTABLERELATIONS r
left join LIMSTABLERELATIONFIELDS rf on r.TABLEID = rf.TABLEID and r.